# Generated by Django 6.0.3 on 2026-10-06 14:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Marca')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Marca de Coche',
                'verbose_name_plural': 'Marcas de Coches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Modelo')),
                ('dealer_id', models.IntegerField(default=1, verbose_name='ID de Concesionario Asignado')),
                ('type', models.CharField(choices=[('SEDAN', 'Sedán'), ('SUV', 'SUV / Todoterreno'), ('WAGON', 'Familiar / Wagon'), ('COUPE', 'Coupé Deportivo'), ('HATCHBACK', 'Compacto / Hatchback'), ('PICKUP', 'Camioneta Pickup'), ('CONVERTIBLE', 'Descapotable / Convertible')], default='SEDAN', max_length=20, verbose_name='Tipo de Vehículo')),
                ('year', models.IntegerField(default=2026, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)], verbose_name='Año de Fabricación')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='dealerships.carmake', verbose_name='Marca de Coche')),
            ],
            options={
                'verbose_name': 'Modelo de Coche',
                'verbose_name_plural': 'Modelos de Coches',
                'ordering': ['make', 'name', '-year'],
            },
        ),
    ]
